import { Dimensions, StyleSheet } from "react-native";
import color from "../../../theme/colors";
import font from "../../../theme/font";

const {width,height} = Dimensions.get('window');

const style = StyleSheet.create({
    container:{
        width:width,
        height:height-font.headerHeight*3,
        backgroundColor:color.backgroundColor,
        alignItems:'center',
    },
    detailsInputcontainer:{
        height:font.headerHeight*1.5,
        width:width,
        backgroundColor:color.backgroundColor,
        marginTop:40
    },
    inputView:{
        height:font.headerHeight,
        width:width-20,
        borderWidth:1,
        borderRadius:10,
        borderColor:color.darkGray,
        backgroundColor:color.backgroundColor,
        marginLeft:10
    },
    inputStyle:{
        fontSize:font.size.font12,
        fontWeight:font.weight.low,
        color:color.borderColor,
        marginLeft:5
    },
    headingText:{
        fontSize:font.size.font10,
        fontWeight:font.weight.semi,
        color:color.darkGray,
        marginLeft:12,
        marginBottom:10
    },
    inputViewDescription:{
        height:font.headerHeight*2,
        width:width-20,
        borderWidth:1,
        borderRadius:10,
        borderColor:color.darkGray,
        backgroundColor:color.backgroundColor,
        marginLeft:10
    },
    inputViewPrice:{
        height:font.headerHeight,
        width:width/5,
        borderWidth:1,
        borderRadius:10,
        borderColor:color.darkGray,
        backgroundColor:color.backgroundColor,
        marginLeft:10
    },
    priceView:{
        height:font.headerHeight*1.5,
        width:width,
        backgroundColor:color.backgroundColor,
        marginTop:40,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-evenly',
        paddingVertical:5
    },
    selectedCategory:{
        flexDirection:'row',
        marginTop:10,
        alignItems:'center'
    },
    changeButton:{
        height:font.headerHeight-25,
        width:font.headerHeight+10,
        borderRadius:5,
        backgroundColor:color.primary,
        alignItems:'center',
        justifyContent:'center',
        marginLeft:10
    },
    buttonText:{
        color:color.white,
        fontSize:font.size.font10
    },
    categoryText:{
        fontSize:font.size.font10,
        fontWeight:font.weight.semi,
        color:color.borderColor
    },
    isveg:{
        alignItems:'center',
        justifyContent:'center',
    },
    isvegText:{
        fontSize:font.size.font10,
        color:color.darkGray,
        marginTop:2
    },
    updateButton:{
        height:font.headerHeight-10,
        width:font.headerHeight*2,
        alignItems:'center',
        justifyContent:'center',
        borderRadius:5,
        backgroundColor:color.tertiary
    },
    updateButtonText:{
        fontSize:font.size.font14,
        fontWeight:font.weight.semi,
        color:color.white
    },
    loader:{
        zIndex:1,
        top:font.size.font16,
    },
    stockView:{
        height:font.headerHeight,
        width:font.headerHeight*2,
        alignItems:'center',
        justifyContent:'center',
        marginTop:20
    },
    headingText1:{
        fontSize:font.size.font12,
        fontWeight:font.weight.semi,
        color:color.darkGray,
        marginTop:5
    },
})

export default style;